openapi: 3.0.3
info:
  title: Økonomimodell API
  description: Økonomimodell API
  version: 1.0.0
servers:
  - url: 'https://okonomimodell-api.intern.dev.nav.no/api/v1'
    description: dev environment

components:
  schemas:
    segmentType:
      type: string
      enum:
        - ARTSKONTO
        - KOSTNADSSTED
        - PRODUKT
        - OPPGAVE
        - FELLES
        - STATSREGNSKAPSKONTO
        - KILDE
        - TILSAGNSAR
        - FRITT_FELT_1
        - FRITT_FELT_2
        - FULLMAKTSKODE
        - REGNSKAPSFORER
    system:
      type: string
      enum:
        - LONN
    relasjon:
      type: object
      properties:
        segmentType:
          $ref: '#/components/schemas/segmentType'
        segmentVerdi:
          type: string
          description: Verdi for segmentet
    segment:
      type: object
      properties:
        segmentType:
          $ref: '#/components/schemas/segmentType'
        segmentVerdi:
          type: string
          description: Verdi for segmentet
        beskrivelse:
          type: string
          description: Beskrivelse for segment
        relasjon:
          type: array
          items:
            $ref: '#/components/schemas/relasjon'
          description: Relasjon til andre segmenter

paths:
  /segmenter:
    get:
      operationId: segments
      summary: Henter alle segmenter
      parameters:
        - name: system
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/system'
      responses:
        '200':
          description: Liste alle segmenter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/segment'
              example:
                - segmentType: ARTSKONTO
                  segmentVerdi: "1234"
                  beskrivelse: "Beskrivelse av segmentet"
                  relasjon:
                    - segmentType: KOSTNADSSTED
                      segmentVerdi: "5678"
        '500':
          description: Internal Server Error

  /segmenter/{segmentType}:
    get:
      operationId: segmentsBySegmentType
      summary: Henter segmenter for et gitt segmentType
      parameters:
        - name: segmentType
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/segmentType'
        - name: system
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/system'
      responses:
        '200':
          description: Liste av segmenter for gitt segmentType
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/segment'
              example:
                - segmentType: ARTSKONTO
                  segmentVerdi: "1234"
                  beskrivelse: "Beskrivelse av segmentet"
                  relasjon:
                    - segmentType: KOSTNADSSTED
                      segmentVerdi: "5678"
        '404':
          description: Fant ikke segmenter for gitt segmentType
        '500':
          description: Internal Server Error

