apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: okonomimodell-api
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: {{image}}
  port: 8080

  envFrom:
    - secret: okonomimodell-api-u1

  prometheus:
    enabled: true
    path: /api/v1/actuator/prometheus

  liveness:
    path: /api/v1/actuator/health/liveness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 3

  readiness:
    path: /api/v1/actuator/health/readiness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 3

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80

  ingresses:
    - https://okonomimodell-api.intern.dev.nav.no

  accessPolicy:
    inbound:
      rules: []
    outbound:
      external: []
      # TODO: Add OeBS hostname here once brunnmursåpning is confirmed
      # external:
      #   - host: <oebs-dev-hostname>

  # envFrom:
  #   - secret: okonomimodell-api-oebs-credentials
  # TODO: Uncomment once okonomimodell-api-oebs-credentials secret is created in team-oebs

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
