apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kontoplan-api
  namespace: oksty
  labels:
    team: oksty
spec:
  image: {{image}}
  port: 8080

  prometheus:
    enabled: true
    path: /actuator/prometheus

  liveness:
    path: /actuator/health/liveness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 3

  readiness:
    path: /actuator/health/readiness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 3

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80

  ingresses:
    - https://kontoplan-api.intern.nav.no

  accessPolicy:
    inbound:
      rules: []
    outbound:
      rules: []

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
