apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: okonomimodell-api
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: {{image}}
  port: 8080

  envFrom:
    - secret: okonomimodell-api-u1

  prometheus:
    enabled: true
    path: /api/v1/actuator/prometheus

  liveness:
    path: /api/v1/actuator/health/liveness
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 3

  readiness:
    path: /api/v1/actuator/health/readiness
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 3

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80

  ingresses:
    - https://okonomimodell-api.intern.dev.nav.no

  accessPolicy:
    inbound:
      rules: []
    outbound:
      external: #todo: Trenger vi alle disse ip adressene, eller holder det med hostnavn?
        - ipv4: 10.53.160.78  # dmv02db01.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.160.80  # dmv02db02.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.160.79  # dmv02db01-vip.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.160.81  # dmv02db02-vip.adeo.no
          ports:
            - port: 1521

        - ipv4: 10.53.160.77  # dmv02-scan.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.160.76  # dmv02-scan.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.160.75  # dmv02-scan.adeo.no
          ports:
            - port: 1521

        - host: dmv02-scan.adeo.no
          ports:
            - port: 1521

  # envFrom:
  #   - secret: okonomimodell-api-oebs-credentials
  # TODO: Uncomment once okonomimodell-api-oebs-credentials secret is created in team-oebs

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
