apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: okonomimodell-api-q1
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: {{image}}
  port: 8080

  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no

  envFrom:
    - secret: okonomimodell-api-q1

  prometheus:
    enabled: true
    path: /api/v1/actuator/prometheus

  liveness:
    path: /api/v1/actuator/health/liveness
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 3

  readiness:
    path: /api/v1/actuator/health/readiness
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 3

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80

  ingresses:
    - https://okonomimodell-api-q1.intern.dev.nav.no

  accessPolicy:
    inbound:
      rules: []
    outbound:
      external:
        - ipv4: 10.53.161.78  # dmv08db01.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.161.80  # dmv08db02.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.161.79  # dmv08db01-vip.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.161.81  # dmv08db02-vip.adeo.no
          ports:
            - port: 1521

        - ipv4: 10.53.161.77  # dmv08-scan.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.161.76  # dmv08-scan.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.161.75  # dmv08-scan.adeo.no
          ports:
            - port: 1521

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
