openapi: 3.0.4
info:
  title: Økonomimodell API
  description: Select server that corresponds to the environment you want to use.
  version: 1.0.0
servers:
  - url: 'https://okonomimodell-api-t1.ekstern.dev.nav.no/api/v1'
    description: test environment
  - url: 'http://localhost:8080/api/v1'
    description: local environment
  - url: 'https://okonomimodell-api-q1.ekstern.dev.nav.no/api/v1'
    description: preprod environment
  - url: 'https://okonomimodell-api.ekstern.nav.no/api/v1'
    description: preprod environment

security:
  - BearerAuth: []

components:

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    segmentType:
      type: string
      enum:
        - ARTSKONTO
        - KOSTNADSSTED
        - PRODUKT
        - OPPGAVE
        - FELLES
        - STATSREGNSKAPSKONTO
        - KILDE
        - TILSAGNSAR
        - FRITT_FELT_1
        - FRITT_FELT_2
        - FULLMAKTSKODE
        - REGNSKAPSFORER
    system:
      type: string
      enum:
        - LONN
    relasjon:
      type: object
      properties:
        segmentType:
          $ref: '#/components/schemas/segmentType'
        segmentVerdi:
          type: string
          description: Value of the segment
    segment:
      type: object
      properties:
        segmentType:
          $ref: '#/components/schemas/segmentType'
        segmentVerdi:
          type: string
          description: Value of the segment
        beskrivelse:
          type: string
          description: Description of the segment
        startDato:
          type: string
          format: date
          description: Start date of the segment on format YYYY-MM-DD
        sluttDato:
          type: string
          format: date
          description: End date of the segment on format YYYY-MM-DD
        aktiv:
          type: boolean
          description: Indicates if the segment is active
        relasjon:
          type: array
          items:
            $ref: '#/components/schemas/relasjon'
          description: Relation to other segments

paths:
  /segmenter:
    get:
      operationId: segments
      security:
        - BearerAuth: []
      summary: Get all segments
      parameters:
        - name: system
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/system'
      responses:
        '200':
          description: List of all segments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/segment'
              example:
                - segmentType: ARTSKONTO
                  segmentVerdi: "1234"
                  beskrivelse: "Beskrivelse av segmentet"
                  startDato: "2024-01-01"
                  sluttDato: "2027-12-31"
                  aktiv: true
                  relasjon:
                    - segmentType: KOSTNADSSTED
                      segmentVerdi: "5678"
        '404':
          description: No segments found for the given segmentType
        '400':
          description: Invalid input parameters
        '500':
          description: Internal Server Error

  /segmenter/{segmentType}:
    get:
      operationId: segmentsBySegmentType
      summary: Get segments by segmentType and optionally filter by lastUpdateDate
      security:
        - BearerAuth: []
      parameters:
        - name: segmentType
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/segmentType'
        - name: lastUpdateDate
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: system
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/system'
      responses:
        '200':
          description: List of segments for given segmentType, optionally filtered by lastUpdateDate
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/segment'
              example:
                - segmentType: ARTSKONTO
                  segmentVerdi: "1234"
                  beskrivelse: "Beskrivelse av segmentet"
                  startDato: "2024-01-01"
                  sluttDato: "2027-12-31"
                  aktiv: true
                  relasjon:
                    - segmentType: KOSTNADSSTED
                      segmentVerdi: "5678"
        '404':
          description: No segments found for the given segmentType
        '400':
          description: Invalid input parameters
        '500':
          description: Internal Server Error

