spring.datasource.url=jdbc:oracle:thin:@dmv43db01.adeo.no:1521/oebst1
spring.datasource.username=${OEBS_DB_USERNAME:placeholder}
spring.datasource.password=${OEBS_DB_PASSWORD:placeholder}
spring.datasource.hikari.initialization-fail-timeout=-1

# Hindrer Hibernate fra a forsoke a validere eller endre databaseskjemaet ved oppstart
spring.jpa.hibernate.ddl-auto=none

logging.level.spring=DEBUG
logging.level.hibernate.SQL=DEBUG
# Gir mer detaljert logging fra Hibernate ved oppstart, nyttig for a diagnostisere krasj
logging.level.org.hibernate=DEBUG
