spring.datasource.url=${OEBS_DB_URL:jdbc:oracle:thin:@//localhost:1521/placeholder}
spring.datasource.username=${OEBS_DB_USERNAME:placeholder}
spring.datasource.password=${OEBS_DB_PASSWORD:placeholder}
spring.datasource.hikari.initialization-fail-timeout=-1
