spring.application.name=kontoplan-api

spring.datasource.url=${OEBS_DB_URL}
spring.datasource.username=${OEBS_DB_USERNAME}
spring.datasource.password=${OEBS_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=unrestricted

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n
