spring.application.name=okonomimodell-api

server.servlet.context-path=/api/v1

spring.datasource.url=${ORACLE_URL}
spring.datasource.username=${OEBS_DB_USERNAME}
spring.datasource.password=${OEBS_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jackson.mapper.sort-properties-alphabetically=false

management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=unrestricted

no.nav.security.jwt.issuer.azuread.discoveryurl=${AZURE_APP_WELL_KNOWN_URL}
no.nav.security.jwt.issuer.azuread.accepted_audience=${AZURE_APP_CLIENT_ID}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.url=/openapi/okonomimodell.yaml

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n
