name: Dependabot auto-merge
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    steps:
      - name: Automerge Dependabot PRs
        id: automerge
        uses: navikt/automerge-dependabot@0e342d25820ca0d2941dcdcad4b7bbb59ad59122
        with:
          token: ${{ github.token }}
          blackout-periods: "Sat,Sun,May 1,May 17,Dec 24-Jan 3"
          update-branch-before-merge: true
          semver-filter: 'patch,minor,unknown'
          auto-approve: true
          merge-method: 'squash'

      - name: Run deploy workflow
        if: steps.automerge.outputs.merged-pr-count != '0'
        run: |
          gh api repos/${{ github.repository }}/dispatches \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -F "event_type=dependabot-deploy"
        env:
          GITHUB_TOKEN: ${{ github.token }}