name: Deploy alerts to NAIS for personhendelse-consumer-oebs
on:
  push:
    branches:
      - main
    paths:
      - .nais/alertconfig-dev.yaml
      - .nais/prometheusrule-dev.yaml
      - .github/workflows/deploy-alerts.yaml

jobs:
  deploy-dev:
    name: Deploy alerts to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - name: Deploy alerts to dev-gcp
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/alertconfig-dev.yaml,.nais/prometheusrule-dev.yaml
